baseURL = "/"
languageCode = "en-us"
title = "Personal Portfolio"
theme = "hugo-ink-master"
paginate = 10



pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	subtitle = "Dylan Tchan | 13206469"

	# Optional 64x64 avatar image.
	avatar = "/images/avatar.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.

[[menu.main]]
name = "Home"
url = "/homepage"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Blog"
url = "/mainpage"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/TE3CH4N"
Stroke = 40

[[params.social]]
name = "Github"
icon = "briefcase"
url = "https://www.linkedin.com/in/dylantchan/"

[[params.social]]
name = "RSS"
icon = "cloud"
url = "https://soundcloud.com/teechand/tracks"
