baseURL = "/"
languageCode = "en-us"
title = "Personal Portfolio | 13206469"
theme = "hugo-ink-master"
paginate = 5




pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	subtitle = "Dylan Tchan | 13206469"

	# Optional 64x64 avatar image.
	avatar = "https://teechan.me/images/yanan.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.

[[menu.main]]
name = "Home"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/TE3CH4N"

[[params.social]]
name = "Github"
icon = "github"
url = "https://www.linkedin.com/in/dylantchan/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://soundcloud.com/teechand/popular-tracks"
